// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJbHgDC15CJUAJExJfjrwdcPLhCf9vX_4',
    appId: '1:647500988143:web:44cf1bcdf65ff74aa0251a',
    messagingSenderId: '647500988143',
    projectId: 'jobphone-20fb7',
    authDomain: 'jobphone-20fb7.firebaseapp.com',
    storageBucket: 'jobphone-20fb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7xEsy72rW5Ahg5AU3NiZzt_pqy9ngXM',
    appId: '1:647500988143:android:e16fbe547f585439a0251a',
    messagingSenderId: '647500988143',
    projectId: 'jobphone-20fb7',
    storageBucket: 'jobphone-20fb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPWuVDceJ5YP082fZcOHiA8zlUNuB63Gs',
    appId: '1:647500988143:ios:fb057ff8e0e2e67ea0251a',
    messagingSenderId: '647500988143',
    projectId: 'jobphone-20fb7',
    storageBucket: 'jobphone-20fb7.appspot.com',
    iosBundleId: 'com.example.jobPhone0907',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPWuVDceJ5YP082fZcOHiA8zlUNuB63Gs',
    appId: '1:647500988143:ios:5e7190c3b05a33b6a0251a',
    messagingSenderId: '647500988143',
    projectId: 'jobphone-20fb7',
    storageBucket: 'jobphone-20fb7.appspot.com',
    iosBundleId: 'com.example.jobPhone',
  );
}
